config/routes.rb
RefactorThis::Application.routes.draw do
  resources :todos
  root :to => "todos#index"
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  
STATUS_CODES = { incomplete: 0, complete: 1, in_progress: 2, moved: 3, deleted: 4, postponed: 5, important: 6 }

  attr_accessible :title, :body, :list_name, :todo_count, :status
  before_save :format_list_name
  
  def status?(status)
    status_code = STATUS_CODES[status.to_sym]
    self.status == status_code
  end

  def status!(new_status)
    status_code = STATUS_CODES[new_status.to_sym]
    self.update_attributes :status => status_code
  end

  class << self

    def all_by_status(status)
      status_code = STATUS_CODES[status.to_sym]
      self.where :status => status_code
    end

    def create_by_status(status)
      status_code = STATUS_CODES[status.to_sym]
      self.create :status => status_code
    end
 
  end

  private
    def format_list_name
      self.list_name = self.list_name.parameterize
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include TaskHelper


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    @todo_lists = @todos.map(&:list_name).uniq
  end

  def new
    @todo = Todo.new
  end

  def show
    @todo = Todo.find params[:id]
  end

  def create
    @todo = Todo.new params[:todo]
    if @todo.save
      update_count
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find params[:id]
  end

  def update
    @todo = Todo.find params[:id]
    if @todo.update_attributes params[:todo]
      redirect_to @todo
    else
      render :edit
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RefactorThis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_todo_form.html.erb
<%= form_for todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :list_name %>
  <%= f.text_field :list_name %>
  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<%= render "todo_form", :todo => @todo %>

app/views/todos/index.html.erb
<%= link_to "new todo", new_todo_path %>
<% @todo_lists.each do |list| %>
  <h2><%= list %></h2>
  <ul>
    <% @todos.each do |todo| %>
      <% if todo.list_name == list %>
        <li>
          <%= link_to "#{todo.title}: #{todo.body}", todo %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/todos/new.html.erb
<%= render "todo_form", :todo => @todo %>

app/views/todos/show.html.erb
<h2><%= @todo.list_name %></h2>
<ul>
  <li><%= @todo.title %></li>
  <li><%= @todo.body %></li>
  <li><%= @todo.todo_count %></li>
</ul>

<%= link_to "edit", edit_todo_path(@todo) %>